export const SITE_CONFIG = {
    name: "Sudhanshu — Full Stack Engineer",
    title: "Sudhanshu | MERN Stack Engineer — Building Scalable Web Products",
    description: "Full Stack Engineer specializing in MERN stack, scalable backend systems, modern frontend architecture, and production deployments.",
    url: "https://sudhanshu.dev",
    ogImage: "/og.png",
    github: "https://github.com/Sudhanshu2246",
    linkedin: "https://www.linkedin.com/in/sudhanshu-gaur-233726228/",
    twitter: "https://x.com/SudhanshuIm",
    email: "sudhanshu2246@gmail.com",
};
export const NAV_LINKS = [
    { label: "About", href: "#about" },
    { label: "Experience", href: "#experience" },
    { label: "Projects", href: "#projects" },
    { label: "Skills", href: "#skills" },
    { label: "Contact", href: "#contact" },
];
export const TECH_STACK = {
    Frontend: [
        "React",
        "Next.js",
        "JavaScript",
        "HTML5",
        "CSS3",
        "Tailwind CSS",
        "GSAP",
        "Framer Motion",
        "React Query",
        "Redux-Toolkit",
        "Context API",
        "React Hook Form",
        "Bootstrap",
    ],
    Backend: [
        "Node.js",
        "Express.js",
        "Socket.io",
        "REST APIs",
        "WebSockets",
    ],
    Database: ["MongoDB", "PostgreSQL", "Redis", "Elasticsearch", "Prisma"],
    DevOps: ["AWS", "Docker", "CI/CD", "Nginx"],
    Tools: ["Postman", "Mongo DB Compass", "VS Code", "GitHub"],
};
export const PROJECTS = [
    {
        id: "maven-jobs",
        title: "Maven Jobs",
        category: "Enterprise Recruitment Platform",
        duration: "Nov 2025 — Present",
        shortDescription: "Designed and developed a production-grade Recruiter Management System that streamlines candidate management, hiring workflows, and recruiter collaboration through scalable MERN architecture.",
        problem: "Recruitment teams struggled with managing thousands of candidate profiles, searching resumes quickly, collaborating in real time, and processing bulk candidate imports efficiently.",
        solution: "Built a scalable MERN application with Elasticsearch-powered search, JWT/OAuth authentication, RBAC, WebSockets, Dockerized deployment, and bulk Excel import functionality.",
        keyFeatures: [
            "Candidate Management",
            "Recruiter Dashboard",
            "Admin Dashboard",
            "Role-Based Access Control",
            "JWT Authentication",
            "OAuth 2.0",
            "Elasticsearch Full-Text Search",
            "Real-Time Notifications",
            "Resume Management",
            "Bulk Excel Upload (500+ records)",
            "Pagination & Advanced Filters",
            "WebSocket Real-Time Updates",
            "Dockerized Deployment",
        ],
        architecture: "MERN Stack · MVC Architecture · RESTful APIs · Elasticsearch · MongoDB · Docker · Socket.io · BullMQ-ready Architecture",
        techStack: [
            "React",
            "Node.js",
            "MongoDB",
            "Express.js",
            "Elasticsearch",
            "Socket.io",
            "Docker",
            "Redis",
            "JWT",
            "BullMQ",
        ],
        performance: [
            "Search performance improved by over 60%",
            "Supports 10,000+ candidate records",
            "Reduced recruiter response time using real-time notifications",
        ],
        challenges: "Optimizing full-text search across thousands of resumes while maintaining real-time collaboration between distributed recruiter teams and processing bulk Excel imports without timeout.",
        results: "Search latency reduced by 60%. System handles 10K+ candidate records efficiently. Real-time notifications cut recruiter response time significantly.",
        image: "/heroSectionImg/project-15.png",
        color: "#00E5A8",
        links: {},
    },
    {
        id: "traveamer",
        title: "Traveamer",
        category: "Corporate Travel Booking Platform",
        duration: "Jan 2025 — Jun 2025",
        status: "LIVE",
        shortDescription: "Built a production-ready corporate travel booking platform integrating TBO APIs to provide enterprise clients with real-time hotel and flight booking services.",
        problem: "Corporate travel booking requires fast hotel searches, large inventory management, and near real-time responses while handling heavy traffic.",
        solution: "Implemented Redis caching, BullMQ background processing, WebSockets streaming, Docker deployment, and CI/CD pipelines to optimize performance.",
        keyFeatures: [
            "Flight Booking",
            "Hotel Booking",
            "Corporate Dashboard",
            "Admin Panel",
            "Multi-Level Approval Workflow",
            "Employee Management",
            "Live Search Streaming",
            "Redis Caching",
            "Background Queue Processing",
            "TBO API Integration",
            "Analytics Dashboard",
            "Docker Deployment",
            "GitHub Actions CI/CD",
        ],
        architecture: "Node.js · Express · MongoDB · Redis · BullMQ · WebSockets · Docker · TBO API",
        techStack: [
            "React",
            "Node.js",
            "MongoDB",
            "Express.js",
            "Redis",
            "BullMQ",
            "Socket.io",
            "Docker",
            "TBO API",
        ],
        performance: [
            "Reduced hotel search response time by over 60%",
            "Streamed live search results using Socket.io",
            "Optimized enterprise-scale booking workflow",
        ],
        challenges: "Integrating with third-party TBO APIs while maintaining low latency, handling concurrent booking requests, and ensuring data consistency across the booking pipeline.",
        results: "Hotel search latency reduced by 60%. Live search results streamed in real time. Enterprise booking workflow fully optimized for scale.",
        image: "/heroSectionImg/project-1.png",
        color: "#64FFDA",
        links: {},
    },
    {
        id: "karoflight",
        title: "KaroFlight",
        category: "Flight & Hotel Booking Platform",
        duration: "Sep 2025 — Dec 2025",
        shortDescription: "Developed a multilingual travel booking platform with secure authentication, multiple dashboards, and real-time integration with TripJack APIs.",
        problem: "Travel applications require real-time inventory, multilingual support, and secure access across different user roles.",
        solution: "Built a MERN platform integrating TripJack APIs, Google Translation APIs, RBAC, Dockerized deployment, and secure JWT authentication.",
        keyFeatures: [
            "Flight Search & Booking",
            "Hotel Search & Booking",
            "Booking & Cancellation",
            "Admin Dashboard",
            "SEO Dashboard",
            "User Dashboard",
            "JWT Authentication",
            "RBAC",
            "Google Translation API",
            "Five Language Support",
            "Docker Deployment",
        ],
        architecture: "React · Node.js · MongoDB · TripJack API · Docker · Google Translation API",
        techStack: [
            "React",
            "Node.js",
            "MongoDB",
            "Express.js",
            "TripJack API",
            "Docker",
            "Google Translation API",
            "JWT",
        ],
        performance: [
            "Multilingual support across 5 languages",
            "Real-time TripJack API integration",
            "Secure multi-role dashboard architecture",
        ],
        challenges: "Integrating multiple third-party APIs for flight and hotel data, implementing translation across five languages without performance degradation, and managing role-based access across three distinct dashboards.",
        results: "Scalable multilingual booking experience supporting five languages. Secure RBAC across admin, SEO, and user dashboards. Real-time inventory via TripJack integration.",
        image: "/heroSectionImg/project-6.png",
        color: "#7DF9FF",
        links: {},
    },
    {
        id: "fleet-management",
        title: "Fleet Management System",
        category: "Real-Time Fleet Tracking Platform",
        duration: "May 2026 — Present",
        shortDescription: "Developed a comprehensive fleet management solution enabling companies to monitor vehicles, manage drivers, and track trips in real time through live GPS updates.",
        problem: "Organizations require centralized management of vehicles, drivers, trip history, and document verification while maintaining live visibility of moving assets.",
        solution: "Designed a scalable MERN application with Google Maps integration, WebSockets, and separate dashboards for Super Admin, Company, and Driver roles.",
        keyFeatures: [
            "Live Vehicle Tracking",
            "Socket.io Real-Time Updates",
            "Google Maps Integration",
            "Trip Analytics & Reports",
            "Driver Ledger Management",
            "Vehicle Assignment",
            "Fleet Reports",
            "Document Management",
            "Role-Based Authentication",
        ],
        architecture: "React · Node.js · Express · MongoDB · Socket.io · Google Maps API · JWT · Docker",
        techStack: [
            "React",
            "Node.js",
            "Express.js",
            "MongoDB",
            "Socket.io",
            "Google Maps API",
            "JWT",
            "Docker",
        ],
        performance: [
            "Real-time vehicle tracking with live GPS updates",
            "Centralized fleet visibility across organizations",
            "Optimized driver and trip management workflows",
        ],
        challenges: "Handling real-time GPS location updates from multiple drivers simultaneously, managing document verification workflows, and building three distinct dashboard experiences from a single backend.",
        results: "Centralized fleet visibility for organizations. Improved driver management and trip monitoring. Real-time operational insights across super admin, company, and driver dashboards.",
        image: "/heroSectionImg/project-12.png",
        color: "#00E5A8",
        links: {},
    },
];
export const EXPERIENCE = [
    {
        company: "Dr Design Pvt Ltd",
        role: "Full Stack Developer Intern",
        period: "Jul 2025 — Present",
        location: "Dehradun, India",
        description: "Building production applications across the full stack — from recruiter platforms to travel booking systems. Working with real users, real data, and real deadlines.",
        highlights: [
            "Built 3+ full-stack applications and 15+ REST APIs from scratch",
            "Integrated JWT authentication with OAuth and RBAC across 4+ modules",
            "Optimized MongoDB queries and indexing, reducing DB latency by 40%",
            "Developed travel booking platform with TBO and TripJack API integrations",
            "Built recruiter system handling 10K+ candidate records with Elasticsearch",
            "Implemented real-time updates with WebSockets for live dashboards",
            "Designed responsive UIs with React and Next.js for mobile and desktop",
            "Set up Redis caching and BullMQ for background job processing",
            "Containerized apps with Docker and configured CI/CD pipelines",
            "Wrote unit and integration tests to maintain code reliability",
        ],
        technologies: [
            "React",
            "Next.js",
            "Node.js",
            "MongoDB",
            "Express.js",
            "Redis",
            "Docker",
            "Elasticsearch",
            "WebSockets",
            "JWT",
        ],
    },
];
export const CERTIFICATES = [
    {
        name: "AWS Solutions Architect Professional",
        issuer: "Amazon Web Services",
        year: "2024",
    },
    {
        name: "Meta Frontend Developer Professional",
        issuer: "Meta",
        year: "2023",
    },
    {
        name: "MongoDB Certified Developer",
        issuer: "MongoDB University",
        year: "2023",
    },
    {
        name: "Google Cloud Professional Architect",
        issuer: "Google",
        year: "2024",
    },
];
export const HERO_PROJECTS = [
    {
        keyword: "MERN",
        title: "RecruitFlow",
        subtitle: "AI Recruitment Platform",
        category: "SaaS",
        tech: ["React", "Node", "MongoDB", "Redis", "Docker"],
        color: "#00E5A8",
        image: "/heroSectionImg/project-1.png",
    },
    {
        keyword: "DEVELOPER",
        title: "TraveAmer",
        subtitle: "Corporate Travel Platform",
        category: "Enterprise",
        tech: ["React", "Node", "Redis", "BullMQ", "Docker"],
        color: "#64FFDA",
        image: "/heroSectionImg/project-2.png",
    },
    {
        keyword: "PRODUCTS",
        title: "SkyBook",
        subtitle: "Flight Booking Platform",
        category: "Travel Tech",
        tech: ["Next.js", "PostgreSQL", "Stripe", "AWS"],
        color: "#7DF9FF",
        image: "/heroSectionImg/project-3.png",
    },
    {
        keyword: "SCALABLE",
        title: "Architecture",
        subtitle: "Redis Cluster Design",
        category: "System Design",
        tech: ["Redis", "Kafka", "Kubernetes", "Go"],
        color: "#00E5A8",
        image: "/heroSectionImg/project-4.png",
    },
    {
        keyword: "STACK",
        title: "DevDash",
        subtitle: "Engineering Analytics",
        category: "Dashboard",
        tech: ["React", "D3.js", "Node", "PostgreSQL"],
        color: "#64FFDA",
        image: "/heroSectionImg/project-5.png",
    },
];
export const GITHUB_STATS = {
    username: "sudhanshu",
    totalRepos: 45,
    totalStars: 320,
    totalCommits: 1200,
    contributions: 850,
    topLanguages: [
        { name: "TypeScript", percentage: 35, color: "#3178C6" },
        { name: "JavaScript", percentage: 25, color: "#F7DF1E" },
        { name: "Python", percentage: 15, color: "#3776AB" },
        { name: "Go", percentage: 10, color: "#00ADD8" },
        { name: "Rust", percentage: 8, color: "#CE422B" },
        { name: "Shell", percentage: 7, color: "#89e051" },
    ],
};
